---
- name: Remove container
  shell: docker-compose -f docker-compose_upgrade.yaml down
  args:
    chdir: /data/docker

- name: Sync files from backup
  shell: rsync -aH --delete /data/docker/backup/app /data/docker/app/

- name: Run old version docker-compose file
  shell: docker-compose -f docker-compose.yaml up -d
  args:
    chdir: /data/docker

- name: Timeout
  pause:
    seconds: 15

- name: Check content
  block:
    - name: Curl
      uri:
        url: "http://localhost:8081"
        return_content: yes
      register: content
      failed_when: "'WordPress' not in content.content"
    - name: Print content
      debug:
        msg: "{{ content }}"
    - name: Send notification to Slack
      slack:
        token: TFBPBNB2L/B0298VAEWLF/Cg15mrgoPMCIzkyIybLNUPDy
        channel: '#aalarm'
        username: 'jenkins'
        msg: 'Rollback SUCCESSFULL'
  rescue:
    - name: Send notification to Slack
      slack:
        token: TFBPBNB2L/B0298VAEWLF/Cg15mrgoPMCIzkyIybLNUPDy 
        channel: '#aalarm'
        username: 'jenkins'
        msg: 'Rollback failed'
