---
- name: aggiungi chiave GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
- name: aggiungi repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 'u+x,g+x'  
  become: yes

- name: Enable docker and add user to docker group
  shell: |
    usermod -aG docker $USER
    chown $USER /var/run/docker.sock
    systemctl enable docker
  args:
    executable: /bin/bash

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
